"""initial schema

Revision ID: 5b7ef028de56
Revises: 
Create Date: 2026-06-19 10:53:19.799444
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7ef028de56'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_company',
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('country', sa.String(length=8), server_default=sa.text("('')"), nullable=False),
    sa.Column('industry', sa.String(length=128), server_default=sa.text("('')"), nullable=False),
    sa.Column('listed', sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('registry', sa.String(length=32), nullable=True),
    sa.Column('registry_id', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('segment', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), server_default=sa.text("('')"), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('canonical_key')
    )
    op.create_table('company',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('country', sa.String(length=8), server_default=sa.text("('')"), nullable=False),
    sa.Column('industry', sa.String(length=128), server_default=sa.text("('')"), nullable=False),
    sa.Column('homepage', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('existence_confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('site_alive', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_key'], ['discovered_company.canonical_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key', name='uq_company_canonical_key')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_canonical_key'), ['canonical_key'], unique=False)

    op.create_table('contact',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('extract_method', sa.String(length=16), server_default=sa.text("'static'"), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_company_id'), ['company_id'], unique=False)

    op.create_table('review_queue',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('candidates', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('assignee', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_company_id'), ['company_id'], unique=False)

    op.create_table('email_validation',
    sa.Column('contact_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('mx', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('domain_match', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_validation')
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_queue_company_id'))

    op.drop_table('review_queue')
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_company_id'))

    op.drop_table('contact')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_canonical_key'))

    op.drop_table('company')
    op.drop_table('discovered_company')
    # ### end Alembic commands ###
